### ISSUE TITLE
@Bundle syntax not correctly handled in child budle not overiding image

### ISSUE THREAD

**Issue by pbeno** [fkrauthan/FkrCssURLRewriteBundle#15]
If I have the ChildBundle which extends ParentBundle by bundle inheritance. And if I want to link image from ParentBundle in ChildBundle css file by  css url with @ParentBundle/images/image.jpg it is rewriten to bundles/child/images/image.jpg even if it doesn't exist in child bundle. So it doesn't provide ParentBundle file if ChildBundle doesn't overide it.

**Comment by fkrauthan** [comment]
Closing this ticket as I don't have time for a rewrite and we couldn't track down why this is happening.
