### ISSUE TITLE
just not working

### ISSUE THREAD

**Issue by garak** [fkrauthan/FkrCssURLRewriteBundle#17]
I tried both bundle syntax and relative syntax, neither is working.

original css
```css
background: url('@AcmeMyBundle/images/body.png') 
background: url('../images/body.png') 
```

generated css
```css
background: url('../../bundles/acmemy/css/@AcmeMyBundle/images/body.png') 
background: url('../../bundles/acmemy/images/body.png') 
```

**Comment by fkrauthan** [comment]
As I don't have time to support asset groups for now I will close this ticket as it is actual more a feature request then a bug.
