### ISSUE TITLE
 Undefined property:$container

### ISSUE THREAD

**Issue by frcho** [fkrauthan/FkrCssURLRewriteBundle#20]
Hi there, the tag 1.0.1 only works good with symfony 3. But in symfony 2.8 or less this bundle get out this error. Please put this in the bundle documentation. Thanks.

php.DEBUG: Undefined property: Fkr\CssURLRewriteBundle\Assetic\Filter\CssURLRewriteFilter::$container {"type":8,"file":"/path/project//vendor/fkr/cssurlrewrite-bundle/Fkr/CssURLRewriteBundle/Assetic/Filter/CssURLRewriteFilter.php","line":118,"level":28928} 

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Error: Call to a member function has() on a non-object   
                                                           

Exception trace:
 () at /home/kijholf/Programas/masterUnlock/dev/vendor/fkr/cssurlrewrite-bundle/Fkr/CssURLRewriteBundle/Assetic/Filter/CssURLRewriteFilter.php:118
 Fkr\CssURLRewriteBundle\Assetic\Filter\CssURLRewriteFilter->calculateSwitchPath()

**Comment by fkrauthan** [comment]
Fixed with release v1.0.2
