### ISSUE TITLE
Bug in Assetic\Filter\CssURLRewriteFilter.php

### ISSUE THREAD

**Issue by stephanwoerner** [fkrauthan/FkrCssURLRewriteBundle#23]
I get error on app/console assetic:dump

 [Symfony\Component\Debug\Exception\FatalErrorException]
  Error: Call to a member function getBaseUrl() on null

I fixed it by changing line 124 to
                if ($request && substr($request->getBaseUrl(), -4) != '.php') {

**Comment by fkrauthan** [comment]
Which PHP Version are you using?

**Comment by stephanwoerner** [comment]
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by fkrauthan** [comment]
Sorry I ment Symfony version^^

**Comment by stephanwoerner** [comment]
2.8

**Comment by fkrauthan** [comment]
It is weird because that code should not execute if you do assetic dump...

I will add your fix which should add a extra layer of protection. After manual applying the fix everything is working fine?

**Comment by stephanwoerner** [comment]
yes, now it works fine.
